---
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# merge bitmasks of default class and unused_buffer if possible
- name: Set default value for facts
  set_fact:
    buffer_merged: false
    mergable_buffers: []
    remaining_buffers: []

- name: Print new iteration message in merge_default_with_unused.yaml
  debug:
    msg: "new iteration with unused_buffers = {{ unused_buffers }} and cos0_schemata = {{ cos0_schemata }}."
  when:
    - unused_buffers | length > 0
    - debug

- name: Add combined bitmasks (default class + unused buffer)
  set_fact:
    mergable_buffers: "{{ mergable_buffers | default([]) + [{'path': item.path, 'schemata': item.schemata, 'combined_mask_hex': combined_mask_hex}] }}"
  vars:
    combined_mask_hex: "{{ cos0_schemata | int(base=16) | dec_or(item.schemata | int(base=16)) | dec2hex }}"
    consecutiveness: "{{ cos0_schemata | int(base=16) | dec_or(item.schemata | int(base=16)) | is_consecutive }}"
  with_items:
    - "{{ unused_buffers }}"
  when: consecutiveness | bool

- name: Print mergable_buffers
  debug:
    var: mergable_buffers
  when:
    - mergable_buffers | length > 0
    - debug

- name: Remaining unused buffers
  set_fact:
    remaining_buffers: "{{ remaining_buffers | default([]) + [{'path': item.path, 'schemata': item.schemata, 'combined_mask_hex': combined_mask_hex}] }}"
  vars:
    combined_mask_hex: "{{ cos0_schemata | int(base=16) | dec_or(item.schemata | int(base=16)) | dec2hex }}"
    consecutiveness: "{{ cos0_schemata | int(base=16) | dec_or(item.schemata | int(base=16)) | is_consecutive }}"
  with_items:
    - "{{ unused_buffers }}"
  when: not consecutiveness | bool

- name: Print remaining_buffers
  debug:
    var: remaining_buffers
  when:
    - remaining_buffers | length > 0
    - debug

- name: Get combined bitmask if 1 mergeable buffer exists
  set_fact:
    cos0_schemata: "{{ mergable_buffers[0].combined_mask_hex }}"
  when: mergable_buffers | length == 1

- name: Print combined bitmask of mergeable buffer and cos0
  debug:
    msg: "Combined bitmask of mergeable buffer and cos0: {{ cos0_schemata }}"
  when:
    - mergable_buffers | length == 1
    - debug

- name: Resize default class with combined bitmask of 1st mergeable buffer
  rdt_schemata:
    cache_level: "{{ level }}"
    bitmask_hex: "{{ mergable_buffers[0].combined_mask_hex }}"
    cos_name: "default"
  become: true
  when: mergable_buffers | length == 1

- name: Get combined bitmask if 2 mergeable buffers exist
  set_fact:
    cos0_schemata: "{{ mergable_buffers[0].combined_mask_hex | int(base=16) | dec_or(mergable_buffers[1].schemata | int(base=16)) | dec2hex }}"
  when: mergable_buffers | length == 2

- name: Print combined bitmask of both mergeable buffers and cos0
  debug:
    msg: "Combined bitmasks of 2 mergeable buffers and cos0: {{ cos0_schemata }}"
  when:
    - mergable_buffers | length == 2
    - debug

- name: Resize default class with combined bitmask of 1st & 2nd mergeable buffer
  rdt_schemata:
    cache_level: "{{ level }}"
    bitmask_hex: "{{ cos0_schemata }}"
    cos_name: "default"
  become: true
  when: mergable_buffers | length == 2

- name: Reinitialize unused_buffers
  set_fact:
    unused_buffers: []
  when: mergable_buffers | length > 0

- name: Set unused_buffers to remaining_buffers (in fact deleting merged buffers)
  set_fact:
    unused_buffers: "{{ unused_buffers | default([]) + [{'path': item.path, 'schemata': item.schemata}] }}"
    buffer_merged: true
  with_items:
    - "{{ remaining_buffers }}"
  when: mergable_buffers | length > 0

- name: Unset buffer_merged if no buffer was merged with cos0
  set_fact:
    buffer_merged: false
  when: mergable_buffers | length == 0 or unused_buffers == []
